### ISSUE TITLE
UNKNOWN_ERROR while indexing makes Indexer never stopping

### ISSUE THREAD

**Issue by Bhaal22** [Bhaal22/whatsclose-indexer#9]
info: publishing concert for Arch Enemy London, United Kingdom
info: publishing venue Wembley The SSE Arena
error:
{ results: [], status: 'UNKNOWN_ERROR' }
[Error: Solvesborg, Sweden]
error: error getting geometry
Solvesborg, Sweden
TypeError: Cannot read property 'results' of undefined
    at e:\dev\perso\git\whatsclose-indexer\src\services\geocoding\GeoCodeService.js:73:21
    at _fulfilled (e:\dev\perso\git\whatsclose-indexer\src\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (e:\dev\perso\git\whatsclose-indexer\src\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (e:\dev\perso\git\whatsclose-indexer\src\node_modules\q\q.js:749:13)
    at e:\dev\perso\git\whatsclose-indexer\src\node_modules\q\q.js:557:44
    at flush (e:\dev\perso\git\whatsclose-indexer\src\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:442:13)
info: publishing concert for Dark Tranquility Clisson, France

**Comment by Bhaal22** [comment]
Need to create a test with Response Mocking !
